
"""hotel bookings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFkhrte6flue8_JUQI7c4QomT7zC8Z85

#Importing Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""#Loading Dataset"""

from google.colab import files

uploaded = files.upload()

df=pd.read_csv('hotel_bookings 2.csv')

"""#Exploratory Data Analysis and Data Cleaning"""

df.head()

df.tail()

df.shape  #to see no of rows and coloumns

df.columns

df.info() #to know the data types

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], format='%d/%m/%Y')

df.describe(include='object')  #generally includes numbericals for descibe but we can use include method to get the data of the object

df.describe(include='object')

for col in df.describe(include= 'object').columns:
  print(col)
  print(df[col].unique())
  print('-'*50)

df.isnull().sum() #to check null values

df.drop(['company','agent'],axis=1, inplace=True)

df.dropna(inplace=True)

df.isnull().sum()

df.describe()

"""### removing outliners like - and adr lo 5400 undi adn -6.38"""

df['adr'].plot(kind='box') #plotting the box

df=df[df['adr']<5000]

"""#analysis and visualization"""

canceled_percentage=df['is_canceled'].value_counts(normalize=True)
print(canceled_percentage)


plt.figure(figsize=(5,4))
plt.title('reservation status count')
plt.bar(['not canceled', 'canceled'], df['is_canceled'].value_counts(),edgecolor='k',width=0.7)
plt.show()

plt.figure(figsize=(8,4))
ax1=sns.countplot(x='hotel', hue='is_canceled', data=df, palette='Blues')
plt.title("reservation status in different hotels", size=20)
plt.xlabel('hotel')
plt.ylabel('no of reservations')

resort_hotel=df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel=df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize=(20,8))  # Specify figsize as a tuple
plt.title('Average Daily Rate in City and Resort Hotel', fontsize=30)
plt.plot(resort_hotel.index,resort_hotel['adr'],label='Resort Hotel')
plt.plot(city_hotel.index,city_hotel['adr'],label='City Hotel')
plt.legend(fontsize=20)
plt.show()

df['month'] = df['reservation_status_date'].dt.month
plt.figure(figsize=(16, 8))
ax1 = sns.countplot(x='month', hue='is_canceled', data=df, palette='bright')
legends_labels, _ = ax1.get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1, 1))
plt.title("Reservation Status per Month", size=20)
plt.xlabel('Month')
plt.ylabel('Number of Reservations')
plt.legend(['Not Canceled', 'Canceled'])
plt.show()

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], format="%d/%m/%Y")
df['month'] = df['reservation_status_date'].dt.month

plt.figure(figsize=(15, 8))
plt.title('ADR per month', fontsize=30)
sns.barplot(x='month', y='adr', data=df[df['is_canceled'] == 1].groupby('month')[['adr']].sum())
plt.show()

canceled_data=df[df['is_canceled']==1]
top_10_country=canceled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title("top 19 countrues with reservation cancelled")
plt.pie(top_10_country, autopct='%.2f',labels=top_10_country.index)
plt.show()

df['market_segment'].value_counts()

df['market_segment'].value_counts(normalize=True)

canceled_data['market_segment'].value_counts(normalize=True)

# Assuming you have defined not_canceled_df and canceled_df earlier
# Assuming df is your original DataFrame containing all reservations
not_canceled_df = df[df['reservation_status'] != 'Canceled']

canceled_df_adr = canceled_data.groupby('reservation_status_date')[['adr']].mean()
canceled_df_adr.reset_index(inplace=True)
canceled_df_adr.sort_values('reservation_status_date', inplace=True)

not_canceled_df_adr = not_canceled_df.groupby('reservation_status_date')[['adr']].mean()
not_canceled_df_adr.reset_index(inplace=True)
not_canceled_df_adr.sort_values('reservation_status_date', inplace=True)

plt.figure(figsize=(20, 6))
plt.title('Average Daily Rate')
plt.plot(not_canceled_df_adr['reservation_status_date'], not_canceled_df_adr['adr'], label='not cancelled')
plt.plot(canceled_df_adr['reservation_status_date'], canceled_df_adr['adr'], label='cancelled')
plt.legend()
plt.show()

canceled_df_adr = canceled_df_adr[(canceled_df_adr["reservation_status_date"] > '2016') & (canceled_df_adr["reservation_status_date"] < '2017-09')]
not_canceled_df_adr = not_canceled_df_adr[(not_canceled_df_adr["reservation_status_date"] > '2016') & (not_canceled_df_adr["reservation_status_date"] < '2017-09')]

plt.figure(figsize=(20, 6))
plt.title('Average Daily Rate', fontsize=30)
plt.plot(not_canceled_df_adr["reservation_status_date"], not_canceled_df_adr['adr'], label='not canceled')
plt.plot(canceled_df_adr["reservation_status_date"], canceled_df_adr['adr'], label='canceled')
plt.legend(fontsize=20)
plt.show()



